In [1]:
# !conda install numpy -y 
# Only required if you have not installed numpy

Solving environment: ...working... done

# All requested packages already installed.



In [2]:
import numpy as np

In [3]:
a = np.array([[1,3],[5,7]])
a
# displays the following result:
# array([[1, 3],
#        [5, 7]])

b = np.array([[2,4],[6,8]])
b
# displays the following result:
# array([[2, 4],
#        [6, 8]])

a + b
# displays the following result
#      array([[ 3,  7],
#             [11, 15]])

array([[ 3,  7],
       [11, 15]])

In [4]:
a = np.array([[1,3],[5,7]])
a
# displays the following result:
# array([[1, 3],
#        [5, 7]])




array([[1, 3],
       [5, 7]])

In [5]:
c = np.array([[2,3,6],[4,5,9],[1,8,7]])
c
# displays the following result:
# array([[2, 3, 6],
#        [4, 5, 9],
#        [1, 8, 7]])

array([[2, 3, 6],
       [4, 5, 9],
       [1, 8, 7]])

In [6]:
a.shape
# displays the following result:
#  (2, 2)



(2, 2)

In [7]:
c.shape
# displays the following result:
#  (3, 3)



(3, 3)

In [8]:
a + c
# displays the following error:
# ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 