In [5]:
import numpy as np

In [7]:
 def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array([inputs])
    inputs_minus_min = input_array
    inputs_div_max = input_array
    
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    # inputs_minus_min = input_array-np.minimum(input_array)

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    # inputs_div_max = inputs_minus_min/np.maximum(inputs_minus_min)

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max

In [8]:
input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])

In [9]:
print (input_array)

[[-1  2  7]]


In [10]:
type(input_array)

numpy.ndarray

In [11]:
type ([-1,2,7])

list

In [12]:
input_array.shape

(1, 3)

In [13]:
mylist=[-1,2,7]

In [14]:
mylist.shape

AttributeError: 'list' object has no attribute 'shape'

In [15]:
mylist.len()

AttributeError: 'list' object has no attribute 'len'

In [16]:
len(mylist)

3

In [19]:
np.min(input_array)

-1

In [20]:
input_array - np.min(input_array)

array([[0, 3, 8]])

In [21]:
type(np.min(input_array))

numpy.int32

In [22]:
input_array - (-1)

array([[0, 3, 8]])