In [1]:
import numpy as np

In [2]:
m = np.array([[1,2,3],[4,5,6]])
m
# displays the following result:
# array([[1, 2, 3],
#        [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
n = m * 0.25
n
# displays the following result:
# array([[ 0.25,  0.5 ,  0.75],
#        [ 1.  ,  1.25,  1.5 ]])

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ]])

In [4]:
m * n
# displays the following result:
# array([[ 0.25,  1.  ,  2.25],
#        [ 4.  ,  6.25,  9.  ]])

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

In [5]:
np.multiply(m, n)   # equivalent to m * n
# displays the following result:
# array([[ 0.25,  1.  ,  2.25],
#        [ 4.  ,  6.25,  9.  ]])

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

In [6]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a
# displays the following result:
# array([[1, 2, 3, 4],
#        [5, 6, 7, 8]])


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
a.shape
# displays the following result:
# (2, 4)

(2, 4)

In [8]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b
# displays the following result:
# array([[ 1,  2,  3],
#        [ 4,  5,  6],
#        [ 7,  8,  9],
#        [10, 11, 12]])


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
b.shape
# displays the following result:
# (4, 3)

(4, 3)

In [10]:
c = np.matmul(a, b)
c
# displays the following result:
# array([[ 70,  80,  90],
#        [158, 184, 210]])


array([[ 70,  80,  90],
       [158, 184, 210]])

In [11]:
c.shape
# displays the following result:
# (2, 3)

(2, 3)

In [12]:
np.matmul(b, a)
# displays the following error:
# ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)